language: php
php:
  - nightly
  - 7.1
  - 7.0
install: composer install
script: phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
